### ISSUE TITLE
Simplify the CSS code for the font-weight property.

### ISSUE THREAD

**Issue by josephtkim** [KarinFK1/prj-rev-bwfs-dasmoto#4]
It is usually a good idea to simplify the CSS code as much as possible. You did a great job doing this for the font-family property. You can simplify the code further by applying it to multiple elements like

```css
h1, .container h2, .price {
  font-weight: bold;
}
```
